# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "amoeba-js-rails"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Amoeba Consulting, LLC."]
  s.date = "2013-01-24"
  s.description = "Amoeba.js is a lightweight JS MVC framework extending Backbone JS giving some extra help."
  s.email = "sayhi@amoe.ba"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".npmignore",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "amoeba-js-rails.gemspec",
    "amoeba.js",
    "amoeba.min.js",
    "grunt.js",
    "lib/amoeba-js-rails.rb",
    "lib/amoeba-js-rails/rails/engine.rb",
    "package.json",
    "spec/index.html",
    "src/amoeba.coffee",
    "src/amoeba/app.coffee",
    "src/amoeba/helpers.coffee",
    "src/amoeba/lib/lookup_context.coffee",
    "src/amoeba/lib/module.coffee",
    "src/amoeba/model.coffee",
    "src/amoeba/paginated_collection.coffee",
    "src/amoeba/router.coffee",
    "src/amoeba/sync.coffee",
    "src/amoeba/template.coffee",
    "src/amoeba/view.coffee",
    "src/amoeba/views/collection.coffee",
    "src/amoeba/views/scrollable_collection.coffee",
    "src/lib/polyfills.js",
    "src/namespace.coffee",
    "vendor/assets/javascripts/amoeba-js.js",
    "vendor/assets/javascripts/amoeba.js",
    "vendor/assets/javascripts/amoeba.min.js"
  ]
  s.homepage = "http://github.com/AmoebaConsulting/amoeba-js"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "A lightweight JS MVC framework extending Backbone JS."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails-backbone>, ["= 0.9.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<terminal-notifier>, ["= 1.4.2"])
    else
      s.add_dependency(%q<rails-backbone>, ["= 0.9.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<terminal-notifier>, ["= 1.4.2"])
    end
  else
    s.add_dependency(%q<rails-backbone>, ["= 0.9.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<terminal-notifier>, ["= 1.4.2"])
  end
end

